# AI Engineer Agent - Grafana Datasources Configuration

apiVersion: 1

datasources:
  # Prometheus - Main metrics source
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "POST"
      customQueryParameters: ""
      
  # PostgreSQL - Main database
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: ai_engineer_agent
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: "disable"
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
      
  # TimescaleDB - Analytics database
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: ai_engineer_analytics
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: "disable"
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
      timescaledb: true
      
  # Elasticsearch - Logs
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "[logstash-]YYYY.MM.DD"
    jsonData:
      interval: "Daily"
      timeField: "@timestamp"
      esVersion: "8.8.0"